### ISSUE TITLE
Remove "Checkout" button from the shipments

### ISSUE THREAD

**Issue by hverdonk** [vsoch/freegenes#84]
As the title states. We don't need to checkout as the shipper, and the button is unnecessary.

Also low priority.

**Comment by vsoch** [comment]
Could you show me a screenshot of the page you are referring to?

**Comment by hverdonk** [comment]
Normally yes, but the shipments aren't appearing on the shipments page right now

**Comment by vsoch** [comment]
oh weird! I think I must have done that :) I'll be able to take a look in about 15 mins.

**Comment by vsoch** [comment]
I think this is fixed could you please look now?

**Comment by hverdonk** [comment]
Nope, I still see it.
<img width="1136" alt="Screen Shot 2019-10-09 at 1 07 42 PM" src="https://user-images.githubusercontent.com/31907124/66516494-fc928c00-ea95-11e9-8df0-d3b6197fc906.png">

**Comment by vsoch** [comment]
oh that's a different one than I thought :)

**Comment by vsoch** [comment]
The problem with hiding it here is that it has to use the boolean for a superuser or staff, and this will mean (forever now into the future) that if you are staff or superuser, you won't have easy access to checkout. What I can do is remove it (by adding the check) and then we can test if it's even an issue - I'm imagining some future time when Marc is trying to create an order on his own, doesn't see it, and gets upset.

**Comment by vsoch** [comment]
Removed.
